# Generated by Django 4.1.5 on 2023-01-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='nucleis',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=1500)),
                ('rate', models.IntegerField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.laptop')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
