# Generated by Django 4.1.5 on 2023-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_laptop_nucleis_comment_laptop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='photo',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
