# Generated by Django 4.1.5 on 2023-02-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_laptop_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=1500)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.laptop')),
            ],
        ),
    ]
