# Generated by Django 4.1.5 on 2023-02-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='photo',
        ),
    ]
